### ISSUE TITLE
请求授权

### ISSUE THREAD

**Issue by drinktoomuchsax** [EliotChen8/ElectroCalc#1]
hallo，请求在[SUSTech-EE-Course-Hero](https://github.com/drinktoomuchsax/SUSTech-EE-Course-Hero)里引用你的项目以及引用你的仓库内容：）

**Comment by EliotChen8** [comment]
当然没问题嗷！！！

但其实我这个做的相当粗糙😭
你们可以收录真正的高手：https://github.com/Gralerfics/Gralculator
